name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: release-notes
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          git-user-name: 'GitHub Actions'
          git-user-email: 'actions@github.com'
          skip-commit: 'true'
          skip-version-file: 'true'
          skip-on-empty: 'false'
          output-file: 'false'

      - name: Create ZIP archive
        run: |
          zip -r nt_lua_emulator.zip . -x ".git/*" ".github/*" ".DS_Store"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: nt_lua_emulator.zip
          name: Release ${{ github.ref_name }}
          body: ${{ steps.release-notes.outputs.clean_changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 