name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP archive
        run: |
          zip -r nt_lua_emulator.zip . -x ".git/*" ".github/*" ".DS_Store"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: nt_lua_emulator.zip
          name: Release ${{ github.ref_name }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 