name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: release-notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP archive
        run: |
          zip -r nt_lua_emulator.zip . -x ".git/*" ".github/*" ".DS_Store"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-notes.outputs.upload_url }}
          asset_path: ./nt_lua_emulator.zip
          asset_name: nt_lua_emulator.zip
          asset_content_type: application/zip 